language: bash

sudo: true

env:
  - VERSION=centos7

services:
  - docker

before_script:
  - env | sort
  - export image="nuocw/staging-environment:$VERSION"

script:
  - test "$(head -n1 Dockerfile)" = "FROM nuocw/buildpack-deps:$VERSION"
  - docker build -t "$image" .

after_script:
  - docker images

# vim:set et ts=2 sw=2:
